# **🔍 Exploratory Data Analysis**

# Objective

The objective of this notebook is to explore the cleaned Superstore dataset and identify important patterns, trends, relationships, and business insights.

The analysis will focus on sales, profit, products, customers, categories, regions, and time-based performance.

---

---

## EDA Questions

1. What is the overall sales and profit performance?
2. Which categories generate the highest sales?
3. Which categories generate the highest profit?
4. Which regions perform best in terms of sales and profit?
5. Which products generate the highest sales?
6. Which customers contribute the most sales?
7. How do discounts relate to profit?
8. How do sales change over time?
9. How long does shipping typically take?
10. Which areas require business attention?

---

# **🔍 EDA — Question 1: Overall Sales & Profit**

In [24]:
import pandas as pd
import numpy as np

# **Load Dataset**

In [25]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
file_path = "/content/drive/MyDrive/Sales_Performance_Analytics/data/Superstore.csv"

df = pd.read_csv(file_path, encoding="latin1")

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df['Shipping Days'] = (
    df['Ship Date'] - df['Order Date']
).dt.days

df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month
df['Order Month Name'] = df['Order Date'].dt.month_name()

# **Overall Sales**

In [27]:
total_sales = df['Sales'].sum()

total_sales

np.float64(2297200.8603000003)

# **Overall Profit**

In [28]:
total_profit = df['Profit'].sum()

total_profit

np.float64(286397.0217)

# **Average Sales & Profit**

In [29]:
average_sales = df['Sales'].mean()
average_profit = df['Profit'].mean()

print("Average Sales:", average_sales)
print("Average Profit:", average_profit)

Average Sales: 229.85800083049833
Average Profit: 28.65689630778467

# **Create Summary**

In [30]:
summary = pd.DataFrame({
    'Metric': [
        'Total Sales',
        'Total Profit',
        'Average Sales',
        'Average Profit'
    ],
    'Value': [
        total_sales,
        total_profit,
        average_sales,
        average_profit
    ]
})

summary

           Metric         Value
0     Total Sales  2.297201e+06
1    Total Profit  2.863970e+05
2   Average Sales  2.298580e+02
3  Average Profit  2.865690e+01

Total Sales

     ↓
Total Profit

     ↓
Average Sales

     ↓
    
Average Profit

# **🔹 Q2 — Category-wise Sales & Profit**

**Category-wise Sales**

In [31]:
category_sales = df.groupby('Category')['Sales'].sum()

category_sales

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

**Category-wise Profit**

In [32]:
category_profit = df.groupby('Category')['Profit'].sum()

category_profit

Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

**Summary**

In [33]:
category_summary = df.groupby('Category').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum')
)

category_summary

                 Total_Sales  Total_Profit
Category
Furniture        741999.7953    18451.2728
Office Supplies  719047.0320   122490.8008
Technology       836154.0330   145454.9481

Category

   ↓

Total Sales

   ↓
   
Total Profit

## Category-wise Sales & Profit Insights

- Technology generated the highest total sales and total profit among all categories.
- Office Supplies generated lower sales than Technology but achieved a strong profit.
- Furniture generated substantial sales but comparatively lower profit.
- The difference between sales and profit across categories requires further analysis.

# **🔹 Q3 — Region-wise Sales & Profit**

In [34]:
region_summary = df.groupby('Region').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum')
)

region_summary

         Total_Sales  Total_Profit
Region
Central  501239.8908    39706.3625
East     678781.2400    91522.7800
South    391721.9050    46749.4303
West     725457.8245   108418.4489

## Region-wise Sales & Profit Insights

- The West region generated the highest total sales and total profit.
- The East region recorded the second-highest sales and profit.
- The South region generated the lowest total sales among all regions.
- The Central region generated higher sales than the South region but comparatively lower profit.

# **🔹 Q4 — Top 10 Products by Sales**

In [35]:
top_products = (
    df.groupby('Product Name')['Sales']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_products

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

## Top 10 Products by Sales — Insights

- Canon imageCLASS 2200 Advanced Copier generated the highest total sales among all products.
- The top-selling products are largely related to office equipment, printers, copiers, and binding systems.
- The Canon imageCLASS 2200 Advanced Copier shows significantly higher sales than the other top-performing products.

# **🔹 Q5 — Top 10 Customers by Sales**

In [36]:
top_customers = (
    df.groupby('Customer Name')['Sales']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_customers

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

## Top 10 Customers by Sales — Insights

- Sean Miller generated the highest total sales among all customers.
- Tamara Chand ranked second in total sales.
- The top customers represent important contributors to overall sales.
- Customer-level sales analysis can help identify high-value customers.

# **🔹 Q6 — Year-wise Sales**

In [37]:
yearly_sales = (
    df.groupby('Order Year')['Sales']
      .sum()
)

yearly_sales

Order Year
2014    484247.4981
2015    470532.5090
2016    609205.5980
2017    733215.2552
Name: Sales, dtype: float64

In [38]:
yearly_sales.sort_values(ascending=False)

Order Year
2017    733215.2552
2016    609205.5980
2014    484247.4981
2015    470532.5090
Name: Sales, dtype: float64

## Year-wise Sales Insights

- 2017 recorded the highest total sales of 733,215.26.
- 2015 recorded the lowest total sales of 470,532.51.
- Sales increased significantly from 2015 to 2016 and continued to grow in 2017.
- The overall trend indicates strong sales growth toward the later years of the dataset.

# **🔹 Q7 — Year-wise Profit**

In [39]:
yearly_profit = (
    df.groupby('Order Year')['Profit']
      .sum()
)

yearly_profit

Order Year
2014    49543.9741
2015    61618.6037
2016    81795.1743
2017    93439.2696
Name: Profit, dtype: float64

## Year-wise Profit Insights

- 2017 recorded the highest total profit of 93,439.27.
- 2014 recorded the lowest total profit of 49,543.97.
- Total profit increased consistently from 2014 to 2017.
- The growth in profit indicates improving overall profitability over the analyzed period.

# **🔹 Q8 — Monthly Sales Trend**

In [40]:
monthly_sales = (
    df.groupby('Order Month')['Sales']
      .sum()
)

monthly_sales

Order Month
1      94924.8356
2      59751.2514
3     205005.4888
4     137762.1286
5     155028.8117
6     152718.6793
7     147238.0970
8     159044.0630
9     307649.9457
10    200322.9847
11    352461.0710
12    325293.5035
Name: Sales, dtype: float64

In [41]:
monthly_sales_named = (
    df.groupby(['Order Month', 'Order Month Name'])['Sales']
      .sum()
      .sort_index()
)

monthly_sales_named

Order Month  Order Month Name
1            January              94924.8356
2            February             59751.2514
3            March               205005.4888
4            April               137762.1286
5            May                 155028.8117
6            June                152718.6793
7            July                147238.0970
8            August              159044.0630
9            September           307649.9457
10           October             200322.9847
11           November            352461.0710
12           December            325293.5035
Name: Sales, dtype: float64

## Monthly Sales Trend — Insights

- November recorded the highest monthly sales of 352,461.07.
- February recorded the lowest monthly sales of 59,751.25.
- September, November, and December recorded strong sales performance.
- Sales were relatively higher during the later months of the year.
- The monthly analysis shows noticeable variation in sales across different months.

# **Q9 — Total Quantity Sold by Category.**

In [42]:
category_quantity = (
    df.groupby('Category')['Quantity']
      .sum()
)

category_quantity

Category
Furniture           8028
Office Supplies    22906
Technology          6939
Name: Quantity, dtype: int64

In [43]:
category_quantity.sort_values(ascending=False)

Category
Office Supplies    22906
Furniture           8028
Technology          6939
Name: Quantity, dtype: int64

## Category-wise Quantity Sold — Insights

- Office Supplies recorded the highest quantity sold with 22,906 units.
- Furniture recorded 8,028 units sold.
- Technology recorded 6,939 units sold.
- Although Office Supplies had the highest quantity sold, Technology generated the highest sales and profit.
- This indicates that sales performance depends not only on quantity sold but also on the value of individual products.

# **🔹 Q10 — Top 10 Products by Profit**

In [44]:
top_profit_products = (
    df.groupby('Product Name')['Profit']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_profit_products

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Ativa V4110MDD Micro-Cut Shredder                                               3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta                                3717.9714
Plantronics Savi W720 Multi-Device Wireless Headset System                      3696.2820
Ibico EPK-21 Electric Binding System                                            3345.2823
Zebra ZM400 Thermal Label Printer                                               3343.5360
Name: Profit, dtype: float64

## Top 10 Products by Profit — Insights

- Canon imageCLASS 2200 Advanced Copier generated the highest total profit of 25,199.93.
- Fellowes PB500 Electric Punch Plastic Comb Binding Machine ranked second in total profit.
- Office equipment such as copiers, printers, and binding systems appear prominently among the top profitable products.
- The analysis highlights products that make a strong contribution to overall profitability.

# **EDA Summary Table**

In [46]:
eda_summary = pd.DataFrame({
    'Metric': [
        'Total Sales',
        'Total Profit',
        'Highest Sales Category',
        'Highest Profit Category',
        'Highest Sales Region',
        'Highest Profit Region',
        'Highest Sales Year',
        'Highest Profit Year',
        'Highest Sales Month',
        'Highest Quantity Category'
    ],
    'Value': [
        df['Sales'].sum(),
        df['Profit'].sum(),
        category_summary['Total_Sales'].idxmax(),
        category_summary['Total_Profit'].idxmax(),
        region_summary['Total_Sales'].idxmax(),
        region_summary['Total_Profit'].idxmax(),
        yearly_sales.idxmax(),
        yearly_profit.idxmax(),
        monthly_sales_named.idxmax(),
        category_quantity.idxmax()
    ]
})

eda_summary

                      Metric            Value
0                Total Sales     2297200.8603
1               Total Profit      286397.0217
2     Highest Sales Category       Technology
3    Highest Profit Category       Technology
4       Highest Sales Region             West
5      Highest Profit Region             West
6         Highest Sales Year             2017
7        Highest Profit Year             2017
8        Highest Sales Month   (11, November)
9  Highest Quantity Category  Office Supplies

## 🔎 Key EDA Findings

### Sales & Profit
- Total sales across the dataset were 2,297,200.86.
- Total profit across the dataset was 286,397.02.
- Technology generated the highest total sales and total profit among the categories.
- The West region recorded the highest total sales and total profit.
- 2017 recorded the highest annual sales and profit.

### Product & Customer Performance
- Canon imageCLASS 2200 Advanced Copier generated the highest total sales and total profit among the analyzed products.
- Sean Miller generated the highest total sales among customers.

### Quantity Performance
- Office Supplies recorded the highest quantity sold with 22,906 units.
- Although Office Supplies had the highest quantity sold, Technology generated the highest sales and profit.

### Monthly Performance
- November recorded the highest monthly sales.
- February recorded the lowest monthly sales.
- Sales were relatively stronger during the later months of the year.

## 📌 EDA Conclusion

The Exploratory Data Analysis provided an overall understanding of sales, profit, product, customer, category, regional, and time-based performance.

The analysis identified the major contributors to sales, profitability, and quantity sold, along with important yearly and monthly sales patterns.

The next stage of the project will present these findings using meaningful visualizations.